### ISSUE TITLE
Implement light and dark themes

### ISSUE THREAD

**Issue by pplancq** [pplancq/shelter-ui#16]
**Is your feature request related to a problem? Please describe :**  
The ShelterUI themes (light and dark) are not implemented, and there’s no system to manage dynamic switching.

**Describe the solution you'd like :**  
- Define CSS variables for light and dark themes:
  ```css
  :root.light-theme {
    --background: var(--gray-50);
    --text-primary: var(--gray-900);
    --brand: var(--blue-500);
  }

  :root.dark-theme {
    --background: var(--gray-850);
    --text-primary: var(--gray-50);
    --brand: var(--blue-700);
  }
  ```
- Ensure these variables apply dynamically to text, backgrounds, and interactive elements.

**Describe alternatives you've considered :**  
Using fixed themes, but this limits flexibility.

**Additional context :**  
Themes must ensure:
- At least 7:1 contrast for text.
- No mixing of light and dark theme colors.
