### ISSUE TITLE
Define typography variables in CSS

### ISSUE THREAD

**Issue by pplancq** [pplancq/shelter-ui#19]
**Is your feature request related to a problem? Please describe :**  
The typography styles are not yet implemented in CSS variables, making it difficult to maintain consistency.

**Describe the solution you'd like :**  
Define CSS variables to centralize font styles:
```css
:root {
  --font-family-display: 'Raleway';
  --font-size-d1: 80px;
  --line-height-d1: 80px;
  --font-weight-bold: 700;
  /* Continue for all variants and styles */
}
```

These variables will be used throughout the design system.

**Describe alternatives you've considered :**  
Hardcoding typography styles directly in components, but this reduces scalability.

**Additional context :**  
Include variables for font size, weight, family, line height, and letter spacing.
