### ISSUE TITLE
Create Sass mixins for typography styles

### ISSUE THREAD

**Issue by pplancq** [pplancq/shelter-ui#20]
**Is your feature request related to a problem? Please describe :**  
Applying raw CSS variables repeatedly across files can lead to duplication and errors.

**Describe the solution you'd like :**  
Develop Sass mixins for Figma typography styles:
```scss
@mixin typography-variant($variant) {
  font-family: var(--font-family-#{$variant});
  font-size: var(--font-size-#{$variant});
  line-height: var(--line-height-#{$variant});
  font-weight: var(--font-weight-bold);
}
```

These mixins will simplify adding typography styles to components and layouts.

**Describe alternatives you've considered :**  
Using utility classes for typography, but mixins offer greater flexibility.

**Additional context :**  
Support variants like `display`, `headings`, `text`, and labels for consistency.
