### ISSUE TITLE
Implement Border System

### ISSUE THREAD

**Issue by pplancq** [pplancq/shelter-ui#23]
**Is your feature request related to a problem? Please describe :**  
The ShelterUI design system currently lacks a standardized border system. Borders and border-radius values are critical to maintaining visual consistency and reinforcing the hierarchy of interface elements.

**Describe the solution you'd like :**  
Define CSS variables for border-radius values based on the progressive scale provided in the design tokens:
- `0px`: No rounding for clean edges, tables, or utility elements.
- `4px`: Light rounding for buttons and forms.
- `8px`: Intermediate rounding for cards and panels.
- `16px`: Strong rounding for modals and large sections.
- `50%`: Fully rounded corners for circular elements like avatars and badges.

These variables will ensure consistent usage across all components and layouts.

**Describe alternatives you've considered :**  
Using arbitrary or fixed values for borders, but this leads to inconsistencies and reduces maintainability.

**Additional context :**  
CSS variables to be added:
```css
:root {
  --border-radius-none: 0px;
  --border-radius-small: 4px;
  --border-radius-medium: 8px;
  --border-radius-large: 16px;
  --border-radius-circle: 50%;
}
```

Additionally:
- Ensure border guidelines are documented for context of use (e.g., 4px for buttons, 16px for calls to action).
- Add examples to Storybook showcasing these border-radius values in various components.
