### ISSUE TITLE
Implement Shadow System

### ISSUE THREAD

**Issue by pplancq** [pplancq/shelter-ui#24]
**Is your feature request related to a problem? Please describe:**  
The ShelterUI design system lacks a centralized shadow system to enhance depth perception and visual hierarchy. Shadows are key to guiding user attention and creating a modern, three-dimensional interface.

**Describe the solution you'd like:**  
Define a shadow system in the CSS package based on the progressive intensities provided in the design tokens:
- **Small Shadow**: `0px 2px 4px rgba(0, 0, 0, 0.1)` for buttons and small interactive elements.
- **Medium Shadow**: `0px 4px 8px rgba(0, 0, 0, 0.15)` for maps or content blocks.
- **Large Shadow**: `0px 6px 16px rgba(0, 0, 0, 0.2)` for highlighted elements like modals.

Ensure rules of use are respected:
- Use lighter shadows for less important components and stronger shadows for highlighted or elevated elements.
- Adapt shadows in dark themes to be more diffuse and subtle to maintain aesthetics.
- Avoid overusing shadows to prevent visual clutter.

**Describe alternatives you've considered:**  
Manually defining shadows within individual components, but this leads to inconsistency and higher maintenance.

**Additional context:**  
CSS variables to implement:
```css
:root {
  --shadow-small: 0px 2px 4px rgba(0, 0, 0, 0.1);
  --shadow-medium: 0px 4px 8px rgba(0, 0, 0, 0.15);
  --shadow-large: 0px 6px 16px rgba(0, 0, 0, 0.2);
}
```

Documentation and examples should be added to Storybook to demonstrate proper usage of shadows across different themes and contexts.
