### ISSUE TITLE
Add icon tokens and CSS style

### ISSUE THREAD

**Issue by pplancq** [pplancq/shelter-ui#27]
**Description :**  
- Define CSS variables for icon sizes and border-radius:
  ```css
  :root {
    --icon-size-small: 20px;
    --icon-size-medium: 24px;
    --icon-size-large: 28px;
    --icon-border-radius-none: 0px;
    --icon-border-radius-circle: 50%;
  }
  ```
- Map tokens directly to icon size and border-radius styles.
